name: starter_kit_ipp
description: -.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^11.1.3
  hive: ^2.2.3
  injectable: ^2.1.2
  intl: ^0.18.0
  meta: ^1.9.1
  logger: ^2.0.2+1
  flutter_screenutil: ^5.9.0
  dio: ^5.3.3
  retrofit: ^4.0.2
  envied: ^0.3.0+3
  lottie: ^2.6.0



dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  lint: ^2.0.1
  injectable_generator: ^2.1.6
  very_good_analysis: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.1
  flutter_app_name: ^0.1.0
  retrofit_generator: ^8.0.0
  envied_generator: ^0.3.0+3


dependency_overrides:
  xml: ^6.3.0

flutter_app_name:
  name: "BreezeBuy"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - .env
  fonts:
    - family: 'CustomIcons'
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
